### ISSUE TITLE
Autologin to SOTA account on start of SOTA operation or on start of PoLo

### ISSUE THREAD

**Issue by DocViper666** [ham2k/app-polo#52] opened 2024-08-11 07:04 UTC
In the current version (August 2024 (pre 10)) one needs to go to settings and hit the 'SOTA (for SOTAwatch self-spotting)' button to login before starting a SOTA operation.
This should happen silently on startup of the app or better only when starting a SOTA operation if credentials are available.

**Comment by kwirk** [comment] 2024-08-11 07:09
Do you have to type in log in details as well, or does it just login after briefly going to the browser?

**Comment by DocViper666** [comment] 2024-08-11 07:14
Currently I have to press the button and it return to the app (I guess after login with SOTA SSO). So just the "button" press would be needed to trigger once.
So I guess on success it could just silently do that for the user. If no credentials are there or there is an error then show the dialog?

**Comment by kwirk** [comment] 2024-08-11 07:25
So it should be silently refreshing the token anyway, so there is a bug. Hard to simulate network issues, which I think may be the cause i.e. thinks account is expired, where really the connection is just flakey.

**Comment by DocViper666** [comment] 2024-08-11 07:46
From my observations the token refresh of SOTA SSO is not working well (does not work in any of my browsers). So I guess just restarting a new login session would be better.

**Comment by kwirk** [comment] 2024-08-11 07:56
Yeah, it's not super robust in browsers either, and wondering if its an issue with tokens not being persisted on SOTA Key Cloak service being restarted, as this persistence is an optional feature that needs enabling from what I've read. I'm not that familiar with Key Cloak, so not really sure...

But if PoLo is logging straight back in without you filling in your credentials in the browser, that means the token in PoLo should have been valid, and PoLo is being a little aggressive assuming it's expired/revoked. Made change in #53.

But as discussed in Discord server, should probably have prompt when opening the app, or starting SOTA activity, to prompt user that token has (really) expired/revoked and they need to log in.

**Comment by DocViper666** [comment] 2024-09-17 17:18
I observation is that it now (latest beta) the connection to the SOTA SSO get lost quite frequently. More often when the cell service is unreliable but also with full reception (reported by a friend of mine).
So not sure how this should be done best. Other apps don't have this issue as it looks.
- Either they login and out for every spot? That's my guess?
- Or they don't try to renew the Key Cloak token and just go for it?
 
I unfortunatly have not enough understanding of the Key Cloak system to help troubleshoot the issue.

**Comment by kwirk** [comment] 2024-10-07 19:51
Added #73 as solution to resolve this. Not sure "offline" access is entirely right permission, but works and see example with some other auth providers that require this for apps as well. Arguably, it is "offline" I believe in sense you aren't in browser, and maybe I misunderstood this before.

**Comment by kwirk** [comment] 2024-10-07 19:59
> Added #73 as solution to resolve this. Not sure "offline" access is entirely right permission, but works and see example with some other auth providers that require this for apps as well. Arguably, it is "offline" I believe in sense you aren't in browser, and maybe I misunderstood this before.

Nevermind...works to pull account data, but not accepted by SOTAWatch for spotting.

**Comment by DocViper666** [comment] 2024-10-07 20:05
Would it be possible to just login / get a new toket every time one submits a spot? Or make sure that in the background when the connection is lost it automatically logins in again?

**Comment by kwirk** [comment] 2024-10-07 20:17
Ah, in fact, that testing revealed a bug in the code. The response code from SOTAWatch is different for an expired token, than the response from getting the account info. So when self-spotting the app wasn't trying to get a new token.

Testing some more before posting fix...as need to wait for token to expire to test it.

**Comment by sd** [comment] 2024-11-01 12:43
This should be fixed with SOTA's new API servers and the latest version of PoLo.

**Closed by sd** 2024-11-01 12:43 UTC
